[[redirects]]
  from = "/github/*"
  to = "/.netlify/functions/github"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[build]
environment = {NODE_VERSION = '16'}

[dev]
targetPort = 3000
autoLaunch = false